
zsh:
  repo: git@github.com:robbyrussell/oh-my-zsh.git
  dest: ~/.omz

  syntax_highlighting:
    repo: git@github.com:zsh-users/zsh-syntax-highlighting.git
    # dest: should go in the zsh.repo/custom/plugins
    #        ~/.rbenv/plugins/ruby-build

fasd:
  repo: git@github.com:clvv/fasd.git
  dest: ~/Developer/Tools/shell/fasd/src

rbenv:
  repo: git@github.com:rbenv/rbenv.git
  dest: ~/.rbenv

  ruby_build:
    repo: git@github.com:rbenv/ruby-build.git
    # dest: should go in the rbenv.dest/plugins/ruby-build
    #        ~/.rbenv/plugins/ruby-build

nvm:
  repo: git@github.com:creationix/nvm.git
  dest: ~/.nvm

vim:
  required:
    dirs:
    - ~/.vim/
    - ~/.vim/colors
    - ~/.vim/autoload/

  plug:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/

