---
- name: git | rpm | install
  tags: git
  yum:  pkg=git state=present
  become: yes
  when: ansible_distribution in ('RedHat', 'Fedora')

- name: git | deb | install
  tags: git
  apt:  pkg=git state=present
  become: yes
  when: ansible_distribution in ('Ubuntu')

- name: git | create git dirs
  tags: git
  file: path={{item}} state=directory
  with_items:
    - ~/Developer/Tools/git/

- name: git | copy config
  tags: git
  copy: src={{item.src}} dest={{ item.dest }}
  with_items:
      - { src: git/gitconfig, dest: ~/.gitconfig }
      - { src: git/templates/, dest: ~/Developer/Tools/git/templates/ }

