---
- name: tmux | create dirs tmux tools
  tags: tmux
  file: path={{item}} state=directory
  with_items:
      - ~/Developer/Tools/tmux/

- name: tmux | git clone powerline to tmux tools
  tags: tmux
  git: repo=git@github.com:powerline/powerline.git
       dest=~/Developer/Tools/tmux/powerline
       accept_hostkey=True

- name: tmux | copy tmux.conf
  tags: tmux
  copy: src={{item.file}} dest={{item.dest}}
  with_items:
      - { file: tmux.conf, dest: ~/.tmux.conf }
