---
- name: vim | ensure present
  tags: vim
  become: yes
  yum: pkg=vim state=present
  when: ansible_distribution in ('Fedora')

- name: vim | ensure present
  tags: vim
  become: yes
  apt: pkg=vim state=present
  when: ansible_distribution in ('Ubuntu')

- name: vim | create vim dirs
  tags: vim
  file: path={{item}} state=directory
  with_items: '{{ vim.required.dirs }}'


- name: vim | download vim plugin manager vim-plug
  tags: vim
  get_url: url={{vim.plug.url}} dest={{vim.plug.dest}}

- name: vim | copy settings
  tags: vim
  copy: src={{item.file}} dest={{item.dest}}
  with_items:
      - { file: vim/vimrc, dest: ~/.vimrc }
      - { file: vim/colors/zenburn.vim, dest: ~/.vim/colors/ }

- name: vim | ycm | fedora | install packages needed for the plugin
  tags: vim
  become: yes
  yum: pkg={{item}} state=present
  with_items:
    - cmake
    - python-devel
    - gcc-c++
  when: ansible_distribution in ('Fedora')

- name: vim | ycm | debian | install packages needed for the plugin
  tags: vim
  become: yes
  apt: pkg={{item}} state=present
  with_items:
    - cmake
    - python3
    - g++
  when: ansible_distribution in ('Ubuntu')

- name: vim | plug install all plugins
  tags:
    - vim
    - vim-plugins
  command: vim -c PlugInstall  -c q -c q

