---
- name: Gather info about hosts
  hosts: dev
  tags: essentials,dev-env
  roles:
    -  common/group_by

- name: Setup VM essential
  hosts: dev:&Ubuntu
  become: yes
  tags: essentials
  roles:
      - distro/ubuntu/essentials

- name: Setup VM essential
  hosts: dev:&Fedora
  become: yes
  tags: essentials
  roles:
      - distro/fedora/essentials

- name: Setup developer home
  hosts: dev
  become: no
  tags: dev-env
  roles:
    - dev/env

