---
- name: Gather info about hosts
  hosts: dev
  tags: essentials,dev-env
  roles:
    -  common/group_by

- name: Setup VM essential
  hosts: dev:&Ubuntu
  become: yes
  tags: install
  roles:
      - distro/ubuntu/essentials
      - distro/ubuntu/privacy
      - distro/ubuntu/tools
      - distro/ubuntu/multimedia

